version: "3.8"
services:
  mysql:
    image: 324048504139.dkr.ecr.us-east-2.amazonaws.com/mysql:8.4.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bankapp
    volumes:
      - bankapp-volume:/var/lib/mysql
    networks:
      - bankapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  application:
    environment:
      - IMAGE_REPOSITORY: 324048504139.dkr.ecr.us-east-2.amazonaws.com/bankapp-dev
      - IMAGE_TAG: 
    image: $IMAGE_REPOSITORY:$IMAGE_TAG
    container_name: Bankapp
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bankapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bankapp
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  bankapp:

volumes:
    bankapp-volume: