apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=  # Base64 for "Test@123"
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjM= # Base64 for "Test@123"
  
